### ISSUE TITLE
Bug fix on geometry calculations for area for structures

### ISSUE THREAD

**Issue by Andrevdb** [landinfotech/civitas-asset-management#119]
Area is not calculating automatically on update/insert for structures

**Comment by Andrevdb** [comment]
@aperrygis @tjaartvdb This seems to be working. I'm guessing that the area field that we were looking at on the Zoom call was on the old QGIS project. I'm going to check on Tjaart's machine but I think if you upgrade to the latest QGIS technician project, it should work.

**Comment by aperryGIS** [comment]
Yay! Thanks. I keep forgetting about the new project because I always have my browser panel closed!

Sent from my iPhone

On Jul 21, 2021, at 3:14 PM, André Van den Berg ***@***.***> wrote:

﻿

@aperryGIS<https://github.com/aperryGIS> @tjaartvdb<https://github.com/tjaartvdb> This seems to be working. I'm guessing that the area field that we were looking at on the Zoom call was on the old QGIS project. I'm going to check on Tjaart's machine but I think if you upgrade to the latest QGIS technician project, it should work.

**Comment by Andrevdb** [comment]
@aperryGIS Just joking! There is a bug!

- [ ] add area property to existing structure_building features

**Comment by Andrevdb** [comment]
Instead of doing something sketchy like this:

```
INSERT INTO feature_property (feature_id,property_id)
	SELECT feature_id,
	8
	FROM structure_building WHERE feature_id IN (

select distinct feature_id
 from feature_property, feature_base
 where (feature_property.feature_id not in (	select feature_id 
						  	from feature_property, feature_base
                       		where property_id = 8 AND
						 		(feature_property.feature_id = feature_base.id) AND
								(feature_base.sub_class_id = 34)))
	AND
feature_base.sub_class_id = 34 AND
feature_base.id = feature_property.feature_id);
```

every time a new property is added to a sub_class, there should be a check on the instead of update/insert trigger functions to see if the property exists already for the feature_id, if it does, then update the record, if it does not, then create a new record.
